export type UserRole = 'Administrador' | 'Operador' | 'Consulta'

export type Screen =
  | 'login'
  | 'dashboard'
  | 'fixed-assets'
  | 'asset-detail'
  | 'asset-form'
  | 'control-materials'
  | 'material-detail'
  | 'processes'
  | 'process-detail'
  | 'new-process'
  | 'transfer'
  | 'responsible-change'
  | 'inventory-sessions'
  | 'inventory-scan'
  | 'inventory-result'
  | 'depreciation'
  | 'depreciation-records'
  | 'revaluation'
  | 'actas'
  | 'acta-preview'
  | 'users'
  | 'user-form'
  | 'system-parameters'
  | 'audit-log'
  | 'reports'
  | 'report-view'
  | 'report-charts'
  | 'write-off'
  | 'identifier-ranges'
  | 'identifier-range-form'
  | 'identifier-range-transfer'
  | 'accounting-entries'
